[package]
name = "openslide-sys"
edition = "2021"
version = "0.1.1"
authors = ["AzHicham <hicham.azimani1@gmail.com>"]
description = "Low-level bindings to the openslide library"
repository = "https://github.com/AzHicham/openslide-sys"
homepage = "https://github.com/AzHicham/openslide-sys"
readme = "README.md"
keywords = ["FFI", "bindings", "openslide"]
categories = ["External FFI bindings"]
license = "MIT/Apache-2.0"
build = "build.rs"

[features]
default = []
dynamic-link = []

[dependencies]

[build-dependencies]
bindgen = "0.63.0"
cc = "1.0.77"
pkg-config = "0.3.26"
