name: Publish
on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always
  RUST_VERSION: 1.82.0

jobs:
  publish:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_VERSION }}
          components: clippy, rustfmt
      - name: Install dependencies
        run: make install-deps-ubuntu-openslide3
      - uses: katyo/publish-crates@v2
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
